### PR TITLE
Fix OnEventStrategy

### LINKED ISSUE #150: OnEventInvokeStrategyPlugin broken
As discussed with @prolic: 

https://github.com/prooph/service-bus/blob/develop/src/Plugin/InvokeStrategy/AbstractInvokeStrategy.php#L35

=> Extend the `AbstractPlugin` instead of the `AbstractInvokeStrategy`

and adjust the code to handle each listener:

```
$handlers = $actionEvent->getParam(EventBus::EVENT_PARAM_EVENT_LISTENERS);

foreach ($handlers as $handler) {
    $this->invoke($handler, $message);
}
```

=> Add testcase

### PR DESCRIPTION
**Pull request by mablae**
Closes #150

### CODE REVIEW

File: src/Plugin/InvokeStrategy/OnEventStrategy.php [hunk 1]
```diff
@@ -22,4 +27,24 @@ public function invoke($handler, $message): void
...
+                foreach ($handlers as $handler) {
+                    $this->invoke($handler, $message);
+                }
+
+                $actionEvent->setParam(MessageBus::EVENT_PARAM_MESSAGE_HANDLED, true);
+            },
+            MessageBus::PRIORITY_INVOKE_HANDLER
+        );
+
+
```
Comment (prolic) [inline src/Plugin/InvokeStrategy/OnEventStrategy.php]: one new line too much

**Comment by prolic** [comment]
LICENSE fill is missing update

**Comment by prolic** [comment]
TestCase?

File: src/Plugin/InvokeStrategy/OnEventStrategy.php [hunk 2]
```diff
@@ -22,4 +26,24 @@ public function invoke($handler, $message): void
...
+    public function attachToMessageBus(MessageBus $messageBus): void
+    {
+        $this->listenerHandlers[] = $messageBus->attach(
+            MessageBus::EVENT_DISPATCH,
+            function (ActionEvent $actionEvent): void {
+                $message = $actionEvent->getParam(MessageBus::EVENT_PARAM_MESSAGE);
+                $handlers = $actionEvent->getParam(EventBus::EVENT_PARAM_EVENT_LISTENERS);
+
+                foreach ($handlers as $handler) {
+                    $this->invoke($handler, $message);
```
Comment (prolic) [inline src/Plugin/InvokeStrategy/OnEventStrategy.php]: can be simply: `$handler->onEvent($message);` and method `public function invoke($handler, $message): void` can be removed.

File: LICENSE.txt [hunk 3]
```diff
@@ -1,4 +1,4 @@
-Copyright (c) 2013, Alexander Miertsch contact@prooph.de
+Copyright (c) 2017, Alexander Miertsch contact@prooph.de
```
Comment (prolic) [inline LICENSE.txt]: should be:

Copyright (c) 2013-2017, prooph software GmbH
Copyright (c) 2015-2017, Sascha-Oliver Prolic

File: src/Plugin/InvokeStrategy/OnEventStrategy.php (hunk 2 above)
Comment (mablae) [inline src/Plugin/InvokeStrategy/OnEventStrategy.php]: okay

Comment (mablae) [inline src/Plugin/InvokeStrategy/OnEventStrategy.php]: Fighting with Prophecy and the Testcase right now.

File: src/Plugin/InvokeStrategy/OnEventStrategy.php [hunk 4]
```diff
@@ -12,7 +12,12 @@
...
-class OnEventStrategy extends AbstractInvokeStrategy
+use Prooph\Common\Event\ActionEvent;
+use Prooph\ServiceBus\EventBus;
+use Prooph\ServiceBus\MessageBus;
+use Prooph\ServiceBus\Plugin\AbstractPlugin;
+
+class OnEventStrategy extends AbstractPlugin
 {
     /**
      * @param mixed $handler
```
Comment (oqq) [inline src/Plugin/InvokeStrategy/OnEventStrategy.php]: Unnecessary doc header parameters could be removed.

File: src/Plugin/InvokeStrategy/OnEventStrategy.php [hunk 5]
```diff
@@ -12,7 +12,12 @@
 
 namespace Prooph\ServiceBus\Plugin\InvokeStrategy;
 
-class OnEventStrategy extends AbstractInvokeStrategy
+use Prooph\Common\Event\ActionEvent;
+use Prooph\ServiceBus\EventBus;
+use Prooph\ServiceBus\MessageBus;
+use Prooph\ServiceBus\Plugin\AbstractPlugin;
+
+class OnEventStrategy extends AbstractPlugin
```
Comment (oqq) [inline src/Plugin/InvokeStrategy/OnEventStrategy.php]: This class could be final, i guess.

File: tests/Plugin/InvokeStrategy/OnEventStrategyTest.php [hunk 6]
```diff
@@ -34,4 +37,23 @@ public function it_invokes_the_on_event_method_of_the_handler(): void
...
+        $prophet = new \Prophecy\Prophet();
+
+        $bus = $prophet->prophesize(EventBus::class);
+        $bus->attach(Argument::type('string'), Argument::type('callable'), Argument::type('integer'))->willReturn(new DefaultListenerHandler(function () {
+        }));
+
+        $onEventStrategy->attachToMessageBus($bus->reveal());
+
+        $bus->attach(Argument::type('string'), Argument::type('callable'), Argument::type('integer'))->shouldHaveBeenCalled();
+        $prophet->checkPredictions();
```
Comment (oqq) [inline tests/Plugin/InvokeStrategy/OnEventStrategyTest.php]: Instead the usage of predictions, you could simple run
```php
$bus->attach(Argument::type('string'), Argument::type('callable'), Argument::type('integer'))
    ->shouldBeCalled()
    ->willReturn(new DefaultListenerHandler(function (): void {}));
```

Comment (oqq) [inline tests/Plugin/InvokeStrategy/OnEventStrategyTest.php]: Instead of manuell run checkPredictions(), you could run
```php
$bus->attach(Argument::type('string'), Argument::type('callable'), Argument::type('integer'))
    ->shouldBeCalled()
    ->willReturn(new DefaultListenerHandler(function () {}));
```

Then checkPredictions() would be executed from PHPUnit.

File: tests/Plugin/InvokeStrategy/OnEventStrategyTest.php [hunk 7]
```diff
@@ -34,4 +37,23 @@ public function it_invokes_the_on_event_method_of_the_handler(): void
...
     }
+
+    /**
+     * @test
+     */
+    public function it_can_be_attached_to_event_bus(): void
+    {
+        $onEventStrategy = new OnEventStrategy();
+
+        $prophet = new \Prophecy\Prophet();
```
Comment (oqq) [inline tests/Plugin/InvokeStrategy/OnEventStrategyTest.php]: This line is unnecessary. See comment below.

File: tests/Plugin/InvokeStrategy/OnEventStrategyTest.php [hunk 8]
```diff
@@ -34,4 +37,23 @@ public function it_invokes_the_on_event_method_of_the_handler(): void
...
+
+        $bus = $prophet->prophesize(EventBus::class);
```
Comment (oqq) [inline tests/Plugin/InvokeStrategy/OnEventStrategyTest.php]: Could be `$this->prophesize()`. See comment below.

File: tests/Plugin/InvokeStrategy/OnEventStrategyTest.php (hunk 6 above)
Comment (mablae) [inline tests/Plugin/InvokeStrategy/OnEventStrategyTest.php]: @oqq Thank you, I will try it!

File: src/Plugin/InvokeStrategy/OnEventStrategy.php (hunk 5 above)
Comment (prolic) [inline src/Plugin/InvokeStrategy/OnEventStrategy.php]: yes, final class please

File: src/Plugin/InvokeStrategy/OnEventStrategy.php [hunk 9]
```diff
@@ -22,4 +27,22 @@ public function invoke($handler, $message): void
     {
         $handler->onEvent($message);
```
Comment (prolic) [inline src/Plugin/InvokeStrategy/OnEventStrategy.php]: remove this method

File: src/Plugin/InvokeStrategy/OnEventStrategy.php (hunk 2 above)
Comment (prolic) [inline src/Plugin/InvokeStrategy/OnEventStrategy.php]: can be simply: `$handler->onEvent($message);`

File: tests/Plugin/InvokeStrategy/OnEventStrategyTest.php [hunk 10]
```diff
@@ -34,4 +37,25 @@ public function it_invokes_the_on_event_method_of_the_handler(): void
...
+        $onEventStrategy = new OnEventStrategy();
+
+        $bus = $this->prophesize(EventBus::class);
+        $bus->attach(Argument::type('string'), Argument::type('callable'), Argument::type('integer'))
+            ->shouldBeCalled()
+            ->willReturn(
+                new DefaultListenerHandler(
+                    function () {
+
+                    }
```
Comment (prolic) [inline tests/Plugin/InvokeStrategy/OnEventStrategyTest.php]:
```
function () {}: void
```

Comment (UFOMelkor) [inline tests/Plugin/InvokeStrategy/OnEventStrategyTest.php]: `{}` on the same line would be against PSR-2 (not sure whether this repository is following PSR-2).

Comment (mablae) [inline tests/Plugin/InvokeStrategy/OnEventStrategyTest.php]: Yeah, php-cs-fixer would complain then, been there already :)

File: src/Plugin/InvokeStrategy/OnEventStrategy.php (hunk 9 above)
Comment (mablae) [inline src/Plugin/InvokeStrategy/OnEventStrategy.php]: Then I need to adjust the testcases, too and mock the handler->onEvent() call, too?

File: src/Plugin/InvokeStrategy/OnEventStrategy.php (hunk 2 above)
Comment (mablae) [inline src/Plugin/InvokeStrategy/OnEventStrategy.php]: Done
